version: '3.9'
name: micros-production

services:
  users-microservice:
    container_name: users-microservice
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: production
    env_file: ./apps/users/.env
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://root:${MONGODB_ROOT_PASSWORD}@mongodb-primary:27017/?directConnection=true&authMechanism=DEFAULT
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3000'
  mailer-microservice:
    container_name: mailer-microservice
    build:
      context: .
      dockerfile: ./apps/mailer/Dockerfile
      target: production
    env_file: ./apps/mailer/.env
    environment:
      - PORT=3001
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
    depends_on:
      - users-microservice
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3001'
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=$MONGODB_REPLICA_SET_KEY
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27018:27017'
  mongodb-secondary:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=$MONGODB_REPLICA_SET_KEY
  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=$MONGODB_REPLICA_SET_KEY
  rabbitmq:
    image: rabbitmq:3
    ports:
      - '5673:5672'

volumes:
  mongodb_master_data:
    driver: local
